.github/workflows/codeql-analysis.yml
.github/workflows/release.yml
README.md

RC.3 version release
- RR-Core update to v2.0.0-RC.3 version (release: [link](https://github.com/spiral/roadrunner/releases/tag/v2.0.0-RC.3))
- Temporal plugin update to v2.0.0-RC.2 version (release: [link](https://github.com/temporalio/roadrunner-temporal/releases/tag/v1.0.0-RC.2))

release(RC.3): Release RC.3

---

.rr.yaml

After https://github.com/spiral/roadrunner/pull/591 publishing description for `http.ssl.root_ca` must be updated.
Option description updated.

config(desc): http.ssl.root_ca is optional now (description updated)

---

.github/workflows/build.yaml

- Update golangci-lint version to the most recent.
- Update version in the linters.yaml
~- [x] All commits in this PR are signed (`git commit -s`).~
~- [x] The reason for this PR is clearly provided (issue no. or explanation).~
~- [x] The description of changes is clear and encompassing.~
~- [x] Any required documentation changes (code and docs) are included in this PR.~
~- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.~
~- [x] All added/changed functionality is tested.~

💻 update(CI): update golangci-lint version in the CI

---

.github/workflows/release.yml
CHANGELOG.md

closes #16 
- ⚡ Add support for the M1 releases

🖥 update(CI): support for the M1 (macOS, arm64) releases

---

.github/workflows/release.yml
CHANGELOG.md
Dockerfile

Feature request #19
- Add support for `linux/arm64` platform for docker image
- Update GitHub action
- Go in `Dockerfile` updated up to `1.16.2`
Closes #19

update(dockerfile): add support for the `linux/arm64` platform, bump GO version

---

CHANGELOG.md
cli/root.go
go.mod
go.sum

closes https://github.com/spiral/roadrunner/issues/613
Dotenv file support added using [joho/godotenv](https://github.com/joho/godotenv) package.

feat(env): add dotenv file support

---

.rr.yaml

Closes https://github.com/spiral/roadrunner/issues/619

upd(rr.yaml): Add comment to the rpc section

---

.github/workflows/release.yml
CHANGELOG.md

- Add support for the Linux/arm64 target (releases), closes #38 
- Update release github action (release.yml), add linux/arm64 target

feat(platform): Add support for the linux/arm64 binaries in the releases

---

.rr.yaml

- Add `kv` and `service` configuration sections
`[Author TODO: add description of changes.]`

upd(.rr.yaml): add new services to the `.rr.yaml`

---

.rr.yaml

Fixing wrong `static` config section level.

fix(config): Config `static` section

---

.editorconfig
TODO.md
schemas/config/1.0.json
schemas/config/2.0.json
schemas/config/readme.md
schemas/readme.md

Json-schemas are useful for unit-testing (tests will be implemented later) and will be used for registration on <https://www.schemastore.org/json/> (use-case - IDE type hinting).
I have been decided to locate schemas inside this repository because this looks like the simplest way to updates them in the future.

feat(docs): JSON schemas

---

.github/workflows/tests.yml
.rr.yaml
CHANGELOG.md
schemas/config/1.0.schema.json
schemas/config/2.0.schema.json
schemas/config/readme.md
schemas/readme.md

- Config file linting enabled
- Schemas for the config file renamed
Closes #56
`[Author TODO: add description of changes.]`

ci(lint): сonfig file linting enabled

---

.github/workflows/release.yml
CHANGELOG.md
README.md

`latest` docker image tag is supported now (but we strongly recommend using a versioned tag (like `1.2.3`) instead)
Closes #57 

ci(docker): latest tag publishing

---

Dockerfile.dev
go.mod
go.sum

closes: #61 
- Add dev Dockerfile with PHP and Xdebug inside.

feat(docker): add dev `Dockerfile.dev` with `PHP8` and `Xdebug` inside

---

CHANGELOG.md
go.mod
go.sum
internal/container/plugins.go

- 2.3.0-beta.2 pre-release
- Update go.mod (add rr v.2.3.0-beta.2)
- Add WebSocket and kv plugins to the standard rr-binary bundle.

feat(pre-release): 2.3.0-beta.2 pre-release

---

.rr.yaml
go.mod
go.sum
internal/container/plugins.go

- Pre-release 2.3.1-beta.1
- Pre-release

feat(pre-release): beta 2.3.1 pre-release

---

.rr.yaml
CHANGELOG.md
go.mod
go.sum

- 2.3.1-beta.3 pre-release
- Update RR in the `go.mod`.
- Update `websockets` part of the `.rr.yaml`.

pre-release: update RR to `v.2.3.1-beta.3`

---

.rr.yaml
CHANGELOG.md
go.mod
go.sum
internal/container/plugins.go

- RR updated to `v.2.3.1-beta.4`
- Update modules
- Add broadcast plugin

feat(pre-release): `v2.3.1-beta.4` pre-release

---

CHANGELOG.md
go.mod
go.sum

- Temporal plugin update
- Update temporal plugin to `v1.0.8-beta.1`

feat(plugin): temporal plugin version update

---

go.mod
go.sum

- Update dependencies.
- Update RR to `v2.3.1-beta.6`
- Update temporal to `v.1.0.8-beta.2`

feat(pre-release): update dependencies

---

.rr.yaml
CHANGELOG.md

closes: #79 
- Add debug key to the config.

fix(config): add `debug` pool key to the `.rr.yaml`

---

.github/workflows/release.yml

Issue #71
**Important**: @rustatian you should make two secrets in this repository:
Name | Description
-------- | ---------------
`GHCR_LOGIN` | Service, your or JD's account name
`GHCR_PASSWORD` | Token for account above with `ghcr` write permission (`write:packages`)
More info: <https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry>
> Note: After the first image pushing do not forget to open the container page and connect it with the current repository.

ci(ghcr, docker): support github packages

---

go.mod
go.sum
internal/cli/workers/render.go

- mismatched number of fields to render in the console for the jobs.
- Add the absent field.

fix(jobs): fix jobs stats fields in the `workers -i` mode

---

.gitignore
.rr.yaml
CHANGELOG.md
go.mod
go.sum
internal/container/plugins.go

- `v2.5.0` alpha-1 pre-release
- Update dependencies.
- Update configuration.

feat(pre-release) `v2.5.0` alpha pre-release 

---

internal/cli/serve/command.go

related: https://github.com/spiral/roadrunner-plugins/issues/32
- Pass the RR version in the `serve` mode.

feat(config): pass RR version to the config plugin

---

.rr.yaml
go.mod
go.sum
schemas/config/2.0.schema.json

- Update dependencies.
- Update schema2.0, add temporal section (ref: https://github.com/spiral/roadrunner-binary/issues/138)

upd(deps): dependencies update

---

schemas/config/2.0.schema.json

- RR 2.7 release
- Update jobs plugin section
- Add cache middleware config

update(schema2): `RR2.7` schema update
